api_key: 'devkey'
api_secret: 'secret'
ws_url: 'ws://localhost:7880'
redis:
  address: 'localhost:6379'
  username: ''
  password: ''
  db: 0
sip_port: 5060
rtp_port: 10000-20000
logging:
  level: debug
